#
###################################
# Site wide configuration
####################################
#
# cloned from: https://github.com/renyuanz/leonids
#
# maybe more updated: https://github.com/bilardi/leonids/
#
#
title: Luiz Satoru Ochi
email: satoru@ic.uff.br
description: Professor Titular do Instituto de Computação - IC/UFF
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Luiz Satoru Ochi
  #avatar: leonids-logo.png
  avatar: satoru-01.jpeg #satoru-site.png
  job: "Professor Titular do Instituto de Computação - IC/UFF"
  # bio: "Endereço Profissional: Av. Gal. Milton Tavares de Souza,, s/n - São Domingos, Niterói - RJ, 24210-346"
  bio:
  email: satoru@ic.uff.br
  disqus-shortname:
  twitter: #username
  facebook: luizsatoru.ochi #satoruff #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: #username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: luiz-satoru-ochi-b9916a23 #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #usernameA simple and awesome blog theme powered by jekyll.
  dribbble: #username
  youtube: LuizSatoru #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

include: ['_pages']
exclude:
  - unused/
theme: jekyll-theme-midnight